dist: trusty
language: go
go: '1.10'
go_import_path: go.mozilla.org/mar
before_install:
- go get github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- make getkeys
- make
- make getmarcorpus testmarcorpus
- goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
