dist: trusty
language: go
go: '1.10'
go_import_path: go.mozilla.org/mar
script:
- wget http://download.cdn.mozilla.net/pub/firefox/releases/60.0.1esr/update/win64/en-US/firefox-60.0esr-60.0.1esr.partial.mar
- go run examples/parse.go firefox-60.0esr-60.0.1esr.partial.mar 2>&1 | grep release1_sha384 | grep 'pass signature 0'
